/*
 测试环境使用 H2 内存数据库，表结构保持和 MySQL users 表同名同字段。
 自动化测试只验证认证链路和 SQL 仓储行为，不依赖本机 MySQL 服务。
*/
CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(64) NOT NULL,
    password_hash VARCHAR(120) NOT NULL,
    real_name VARCHAR(64),
    phone VARCHAR(32),
    mail VARCHAR(120),
    avatar VARCHAR(500),
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    deleted INT NOT NULL DEFAULT 0,
    CONSTRAINT uk_users_username UNIQUE (username)
);

CREATE TABLE IF NOT EXISTS uploaded_file (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    file_id VARCHAR(80) NOT NULL,
    username VARCHAR(64) NOT NULL,
    file_name VARCHAR(120) NOT NULL,
    content_type VARCHAR(120),
    file_size BIGINT NOT NULL DEFAULT 0,
    document_type VARCHAR(32) NOT NULL,
    text_content CLOB NOT NULL,
    summary VARCHAR(1000),
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    deleted INT NOT NULL DEFAULT 0,
    CONSTRAINT uk_uploaded_file_file_id UNIQUE (file_id)
);

CREATE TABLE IF NOT EXISTS interview_record (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id VARCHAR(80) NOT NULL,
    username VARCHAR(64) NOT NULL,
    resume_id VARCHAR(80) NOT NULL,
    job_title VARCHAR(120) NOT NULL,
    status VARCHAR(32) NOT NULL,
    question_count INT NOT NULL DEFAULT 0,
    answered_count INT NOT NULL DEFAULT 0,
    total_score INT,
    report_summary VARCHAR(2000),
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    deleted INT NOT NULL DEFAULT 0,
    CONSTRAINT uk_interview_record_session_id UNIQUE (session_id)
);

CREATE TABLE IF NOT EXISTS knowledge_document (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_id VARCHAR(80) NOT NULL,
    username VARCHAR(64) NOT NULL,
    source_id VARCHAR(80) NOT NULL,
    document_type VARCHAR(40) NOT NULL,
    title VARCHAR(200) NOT NULL,
    tags VARCHAR(500),
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    deleted INT NOT NULL DEFAULT 0,
    CONSTRAINT uk_knowledge_document_document_id UNIQUE (document_id)
);

CREATE TABLE IF NOT EXISTS knowledge_chunk (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    chunk_id VARCHAR(80) NOT NULL,
    document_id VARCHAR(80) NOT NULL,
    username VARCHAR(64) NOT NULL,
    source_id VARCHAR(80) NOT NULL,
    document_type VARCHAR(40) NOT NULL,
    section_name VARCHAR(80) NOT NULL,
    chunk_index INT NOT NULL DEFAULT 0,
    section_order INT NOT NULL DEFAULT 0,
    content CLOB NOT NULL,
    summary VARCHAR(1000),
    tags VARCHAR(500),
    metadata_json CLOB,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    deleted INT NOT NULL DEFAULT 0,
    CONSTRAINT uk_knowledge_chunk_chunk_id UNIQUE (chunk_id)
);

CREATE TABLE IF NOT EXISTS evaluation_run (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id VARCHAR(80) NOT NULL,
    username VARCHAR(64) NOT NULL,
    dataset_name VARCHAR(200) NOT NULL,
    total_cases INT NOT NULL DEFAULT 0,
    baseline_summary_json CLOB,
    rag_without_rerank_summary_json CLOB,
    rag_with_rerank_summary_json CLOB,
    self_check_rag_summary_json CLOB,
    report_json_path VARCHAR(500),
    report_markdown_path VARCHAR(500),
    created_at TIMESTAMP NOT NULL,
    completed_at TIMESTAMP NOT NULL,
    deleted INT NOT NULL DEFAULT 0,
    CONSTRAINT uk_evaluation_run_run_id UNIQUE (run_id)
);

CREATE TABLE IF NOT EXISTS evaluation_case_result (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id VARCHAR(80) NOT NULL,
    case_id VARCHAR(80) NOT NULL,
    strategy VARCHAR(60) NOT NULL,
    category VARCHAR(80),
    question VARCHAR(1000) NOT NULL,
    answer CLOB,
    ground_truth CLOB NOT NULL,
    cited_evidence_ids VARCHAR(1000),
    answer_correct INT NOT NULL DEFAULT 0,
    hallucinated INT NOT NULL DEFAULT 0,
    citation_correct INT NOT NULL DEFAULT 0,
    latency_ms BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL
);
