/*
 测试环境使用 H2 内存数据库，表结构保持和 MySQL users 表同名同字段。
 自动化测试只验证认证链路和 SQL 仓储行为，不依赖本机 MySQL 服务。
*/
CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(64) NOT NULL,
    password_hash VARCHAR(120) NOT NULL,
    real_name VARCHAR(64),
    phone VARCHAR(32),
    mail VARCHAR(120),
    avatar VARCHAR(500),
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    deleted INT NOT NULL DEFAULT 0,
    CONSTRAINT uk_users_username UNIQUE (username)
);
