/*
 测试环境使用 H2 内存数据库，表结构保持和 MySQL users 表同名同字段。
 自动化测试只验证认证链路和 SQL 仓储行为，不依赖本机 MySQL 服务。
*/
CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(64) NOT NULL,
    password_hash VARCHAR(120) NOT NULL,
    real_name VARCHAR(64),
    phone VARCHAR(32),
    mail VARCHAR(120),
    avatar VARCHAR(500),
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    deleted INT NOT NULL DEFAULT 0,
    CONSTRAINT uk_users_username UNIQUE (username)
);

CREATE TABLE IF NOT EXISTS uploaded_file (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    file_id VARCHAR(80) NOT NULL,
    username VARCHAR(64) NOT NULL,
    file_name VARCHAR(120) NOT NULL,
    content_type VARCHAR(120),
    file_size BIGINT NOT NULL DEFAULT 0,
    document_type VARCHAR(32) NOT NULL,
    text_content CLOB NOT NULL,
    summary VARCHAR(1000),
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    deleted INT NOT NULL DEFAULT 0,
    CONSTRAINT uk_uploaded_file_file_id UNIQUE (file_id)
);

CREATE TABLE IF NOT EXISTS interview_record (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id VARCHAR(80) NOT NULL,
    username VARCHAR(64) NOT NULL,
    resume_id VARCHAR(80) NOT NULL,
    job_title VARCHAR(120) NOT NULL,
    status VARCHAR(32) NOT NULL,
    question_count INT NOT NULL DEFAULT 0,
    answered_count INT NOT NULL DEFAULT 0,
    total_score INT,
    report_summary VARCHAR(2000),
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    deleted INT NOT NULL DEFAULT 0,
    CONSTRAINT uk_interview_record_session_id UNIQUE (session_id)
);
